---
title: "Week 2 Lecture Notes"
author: "Lynnsha Jing Huang"
date: "Friday, August 14, 2015"
output: html_document
runtime: shiny
---
### Control Structures
Control structures in R allow you to control the flow of execution of the program, depending on runtime conditions.

- **if.else** : testing a condition
- **for**: execute a loop a fixed number of times
- **while**: execute a loop while a condition is true
- **repeat**: execute an infinite loop

Most control structures are not used in interactive sessions, but rather when writing functions or longer expressions.

####1. If-else ####
```
>if(<condition>) {
>## do something
} else {
 ## do something else
}
if(<condition1>) {
 ## do something
} else if(<condition2>) {
 ## do something different
} else {
 ## do something different
```
####2. For loops #### 

**for** loops take an interator variable and assign it successive values from a sequence or vector. For loops are most commonly for iterating over the elements of an object(list, vector, etc)

```
for(i in 1:10) {
 print(i)
}
```
This loop takes the **i** variable and in each iteration of the loop gives it values 1,2,3,..., 10 and then exits.

These three loops have the same behavior

```{R}
x <- c("a", "b", "c", "d")
for(i in 1:4) {
 print(x[i])
}
for(i in seq_along(x)) {
 print(x[i])
}
for(letter in x) {
 print(letter)
}
for(i in 1:4) print(x[i])
```
##### Nested for loops #####
**for** loops can be nested.
```{R}
x <- matrix(1:6, 2, 3)
for(i in seq_len(nrow(x))) {
 for(j in seq_len(ncol(x))) {
 print(x[i, j])
 }
}
```
Be careful with nesting though, nesting beyond 2-3 levels is often very difficult to read/understand.

#### 3.While loops ####
##### While ####
while loops begin by testing a condition. If it is true, then they execute the loop body. Once the loop body is executed, the condition is tested again, and so forth.

```{R}
count <- 0
while(count < 10) {
 print(count)
 count <- count + 1
}
```
while loops can potentially result in infinite loops if not weitten properly.Use with care!

sometimes there will be more than one condition in the test,

```{R}
z <- 5
while(z >= 3 && z <= 10) {
 print(z)
 coin <- rbinom(1, 1, 0.5)
 if(coin == 1) { ## random walk
 z <- z + 1
 } else {
 z <- z - 1
 }
}
```
####4.Repeat, Next,Break ####
Repeat initiates an infinite loop; these are not commonly used in statistical applications but they do have their uses. The only way to exit a **repeat** loop is to call **break**.

```
x0 <- 1
tol <- 1e-8
repeat {
 x1 <- computeEstimate()
 if(abs(x1 - x0) < tol) {
 break
 } else {
 x0 <- x1
 }
}
```
The loops is a bit dangerous because there's no gurantee if it will stop. Better to set a hard limit on the number of iterations(e.g. using a for loop) and then report whether convergence was achieved or not.

##### next, return #####
**next** is used to skip an iteration of a loop

```{R}
for(i in 1:100) {
 if(i <= 20) {
 ## Skip the first 20 iterations
 next
 }
 ## Do something here
}

```
**return** signals that a function should exit and return a given value.

summary

+ control structures like **if**, **while**, and **for** allow you to control the flow of an E program.
+ infinite loops should generally be avoided, even if they are theoretically correct.
+ control structures mentioned here are primarily useful for writing programs; for command-line interactive work, the "apply functions are more useful.

### Functions ###
Functions are created using th **function()** directive and are stored as R objects just like anything else. In particular, they are R objects of class "function".

```
f <- function(<arguments>) {
 ## Do something interesting
}
```
Functions in R are "first class objects", which means that they can be treated much like any other R object. Importantly,

+ Functions can be passed as arguments to other functions.
+ Functions can be nested, so that you can define a function inside of another function
+ The return value of a function is the last expression in the function body to be evaluated.

#### Function Arguments ####
Functions have named arguments which potentially have defaulted values.

+ The *formal arguments* are the arguments included in the function definition
+ The **formals** function returns a list of all the formal arguments of a function
+ Not every function call in R makes use of all the formal argurments
+ Function arguments can be *missing* or might have default values

#### Argument Matching ####
R function arguments can be matched positionally or by names. So the following calls to *sd* are all equivalent 

```
> mydata <- rnorm(100)
> sd(mydata)
> sd(x = mydata)
> sd(x = mydata, na.rm = FALSE)
> sd(na.rm = FALSE, x = mydata)
> sd(na.rm = FALSE, mydata)

```
Even though it's legal, it's not recommended to mess around the order of the arguments too much, since it can lead to some confusion.

You can mix positional matching with matching by name. When an argument is matched by name, it is "taken out" of the argument list and the remainng unnamed arguments are matched in the order that they are listed in the function definition.

```
> args(lm)
function (formula, data, subset, weights, na.action,
 method = "qr", model = TRUE, x = FALSE,
 y = FALSE, qr = TRUE, singular.ok = TRUE,
 contrasts = NULL, offset, ...)
```
The following two calls are equivalent.

```
lm(data = mydata, y ~ x, model = FALSE, 1:100)
lm(y ~ x, mydata, 1:100, model = FALSE)

```
+ Most of the time, named arguments are useful on the command line when you have  along argument list and you want to use the defauts for everything except for an argument near the end of the list.
+ Named arguments also help if you can remember the name of the argument and not its position on the argument list(plotting is a good example).

Function arguments can also be *partially* matche, which is useful for interactive work. The order of operations when given an argument is 

1. check for exact match for a named argument
2. check for a partial match
3. check for a positional match

In addition to not specifying a default value, you can also set an argument value to **NULL**.

#### The "..." Argument ####
The ...argument is also necessary when the number of arguments passed to the function cannot be known in advance.

```
> args(paste)
function (..., sep = " ", collapse = NULL)
> args(cat)
function (..., file = "", sep = " ", fill = FALSE,
 labels = NULL, append = FALSE)

```
#### Arguments Coming After the "..." Argument ####
One catch with ... is that any arguments that appear *after*... on the arggument list must be named explicitly and cannot be partially matched.

```
> args(paste)
function (..., sep = " ", collapse = NULL)
> paste("a", "b", sep = ":")
[1] "a:b"
> paste("a", "b", se = ":")
[1] "a b :"

```
### Scoping Rules ###
#### Symbol Binding ####
##### A Diversion on Binding Values to Symbol #####
How does R know which value to assign to which symbol? 
When R tried to bind a value to a symbol, it searches a series of **enviornments** to find the appropriate value. When you are working on the command line and need to retrieve the value of an R object, the order is roughly

1. Search the global environment for a symbol name matching the one requested.
2. Search the namespaces of each of the packages on the search list,

The search list can be found by using the **search** function

```
> search()
[1] ".GlobalEnv" "package:stats" "package:graphics"
[4] "package:grDevices" "package:utils" "package:datasets"
[7] "package:methods" "Autoloads" "package:base"

```
#### Binding Values to Symbol ####

* The *global environment* or the user's workspace is always the first element of the search list and the *base* package is always the last.
* The order of the packages on the search list matters!
* User's can configute which packages get loaded on startup so you cannot assume that there will be a set list of packages available. 
* When a user loads packag with **library** the namespace of that package gets put in position 2 of the search list (by default) and everything else gets shifted down the list.
* Note that R has separate namespaces for functions and non-functions so it's possible to have an object named c and a function named c. 
 
##### Scoping Rules #####
The scoping rules for R are the main feature that make it different from the original S language.

* The scoping rules determine how a value is associated with a free variable in a function
* R uses *lexical scoping* or *static scoping*. A commin alternative is *dynamic scoping*. 
* Related to the scoping rules is how R uses the search *list* to bind a value to a symbol.
* Lexical scoping turns out to be particularlly useful for simplifying statistical computations.

##### Lexical Scoping #####
Consider the following function.
```
f <- function(x, y) {
 x^2 + y / z
}
```
This function has 2 formal arguments **x** and **y**. In the body of the function there is another symbol **z**. In this case **z** is called a *free variable*. The scoping rules of a language determine how values are assigned to free variables.Free variables are not formal arguments and are not local variables (assigned insided the function body).

Lexical scoping in R means that 
*the values of free variables are searched for in the enviornment in which the function was defined.*

**What is an environment?**

* An *environment* is a collection of (symbol, value) pairs, i.e. **x** is a symbol and **3.14** might be its value.
* Every environment has a parent environment; it is possible for an environment to have multiple "children"
* the only environment without a parent is the empty environment
* A function + an environment = a *closure* or *function closure*

Searching for the value for a free variable:

* If the value of a symbol is not found in the environment in which a function was defined, then the search is continued in the *parent environment*.
* The search continues down the sequence of parent environments until we hit the *top-level environment*; ths usually the global environment(workspace) or the namespace of a pacakge.
* After the top-level environment, the search continues down the search list until we hit the *empty environment*. If a value for a given symbol cannot be found once the empty environment is arrived at, then an error is thrown.

### Application: Optimization ###

* Optimization routines in R like **optim**, **nlm**, **optimize** require you to pass a function whose argument is a vector of parameters(e.g. a log-likelihood)
* However, an object function might depend on a host of other things besides its parameter(like data)
* When writing software which does optimization, it may be desirable to allow the user to hold certain parameters fixed.

#### Maximizing a Normal Likelihood ####
write a "constructor" function

```{R}
make.NegLogLik <- function(data, fixed=c(FALSE,FALSE)) {
 params <- fixed
 function(p) {
 params[!fixed] <- p
 mu <- params[1]
 sigma <- params[2]
 a <- -0.5*length(data)*log(2*pi*sigma^2)
 b <- -0.5*sum((data-mu)^2) / (sigma^2)
 -(a + b)
 }
}
```
*Note*: Optimization functions in R *minimized* functions, so you need to use the negative log-likelihood.

```
> set.seed(1); normals <- rnorm(100, 1, 2)
> nLL <- make.NegLogLik(normals)
> nLL
function(p) {
 params[!fixed] <- p
 mu <- params[1]
 sigma <- params[2]
 a <- -0.5*length(data)*log(2*pi*sigma^2)
 b <- -0.5*sum((data-mu)^2) / (sigma^2)
 -(a + b)
 }
<environment: 0x165b1a4>
> ls(environment(nLL))
[1] "data" "fixed" "params"

```

#### Estimating Parameters ####

```
> optim(c(mu = 0, sigma = 1), nLL)$par
 mu sigma
1.218239 1.787343

```
Fixing σ = 2

```
> nLL <- make.NegLogLik(normals, c(FALSE, 2))
> optimize(nLL, c(-1, 3))$minimum
[1] 1.217775

```
Fixing  μ = 1

```
> nLL <- make.NegLogLik(normals, c(1, FALSE))
> optimize(nLL, c(1e-6, 10))$minimum
[1] 1.800596

```
#### plotting the Likelihood ####

```
nLL <- make.NegLogLik(normals, c(1, FALSE))
x <- seq(1.7, 1.9, len = 100)
y <- sapply(x, nLL)
plot(x, exp(-(y - min(y))), type = "l")
nLL <- make.NegLogLik(normals, c(FALSE, 2))
x <- seq(0.5, 1.5, len = 100)
y <- sapply(x, nLL)
plot(x, exp(-(y - min(y))), type = "l")

```
#### Lexical Scoping Summary ####
* Objective functions can be "built" which contain all of the necessary data for evaluating the function
* No need to carry arounf long argument lists- useful for interactive and exploratory work.
* Code can be simplified and cleaned up
* Reference: Robert Gentleman and Ross Ihaka (2000). "Lexical Scope and Statistical Computing," JCGS, 9, 491-508.

### Dates and Times in R ###
R has developed a special representation of dates and times.

* Dates are represented by the **Date** class
* Times are represented by the **POSIXct** or the **POSIXlt** class
* Dates are stored internally as the number of days since 1970-01-01
* Times are stored internally as the number of seconds since 1970-01-01

#### Dates in R ####

Dates are represented by the Date class and can be coerced from a character string using the **as.date()**function.

```{R}
x <- as.Date("1970-01-01")
x
## [1] "1970-01-01"
unclass(x)
## [1] 0
unclass(as.Date("1970-01-02"))
## [1] 1
```
#### Times in R ####

Times are represented using the **POSIXct** or **POSIXlt** class

* **POSIXct** is just a very large integer under the hood; it use a useful class when you want to store times in something like a data frame
* **POSIXlt** is a list underneath and it stores a bunch of other useful information like the day of the week, day of the year, month, day of the month

There are a number of genetic functions that work on dates and times.

* **weekday**s: give the day of the week
* **months**: give the month name
* **quarters**: give the quarter number("Q1","Q2","Q3", or "Q4")

#### Times in R ####

Times can be coerced from a character string using the **as. POSIXLT** or **as.POSIXct** function.

```{R}
x <- Sys.time()
x
## [1] "2013-01-24 22:04:14 EST"
p <- as.POSIXlt(x)
names(unclass(p))
## [1] "sec" "min" "hour" "mday" "mon"
## [6] "year" "wday" "yday" "isdst"
p$sec
## [1] 14.34
```
You can also use the **POSIXct** format

```
x <- Sys.time()
x ## Already in ‘POSIXct’ format
## [1] "2013-01-24 22:04:14 EST"
unclass(x)
## [1] 1359083054
x$sec
## Error: $ operator is invalid for atomic vectors
p <- as.POSIXlt(x)
p$sec
## [1] 14.37
```

Finally, there is the **Strptime** function in case your dates are written in a different format

```{R}
datestring <- c("January 10, 2012 10:40", "December 9, 2011 9:10")
x <- strptime(datestring, "%B %d, %Y %H:%M")
x
```
```{R}
class(x)
```
#### Operations on Dates and Times ####

You can use mathematical operations on dates and times, just + and -, can do comparisons too (i.e. ==, <=)

```
x <- as.Date("2012-01-01")
y <- strptime("9 Jan 2011 11:34:21", "%d %b %Y %H:%M:%S")
x-y
## Warning: Incompatible methods ("-.Date",
## "-.POSIXt") for "-"
## Error: non-numeric argument to binary operator
x <- as.POSIXlt(x)
x-y
## Time difference of 356.3 days

```
Even keeps track of leap years, leap seconds, daylight savings, and time zones.

```
x <- as.Date("2012-03-01") y <- as.Date("2012-02-28")
x-y
## Time difference of 2 days
x <- as.POSIXct("2012-10-25 01:00:00")
y <- as.POSIXct("2012-10-25 06:00:00", tz = "GMT")
y-x
## Time difference of 1 hours
```
#### Summary####

* Dates and times have special classes in R that allow for numerical and statistical calculations
* Dates use the Date class
* Times use the POSIXct and POSIXlt class
* Character strings can be coerced to Date/Time classes using the strptime function or the **as.Date**, **as.POSIXlt**, or **as.POSIXct**
·




